application: cs360contacts
version: 1
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: public/js
- url: /css
  static_dir: public/css
- url: /favicon.ico
  static_dir: public/favicon.ico
- url: /.*
  script: contactlist.py
